# Bài tập 2 - Thư viện NumPy và pandas

*(Thống kê máy tính và ứng dụng - ĐTTX Kì 1 2024-2025)*

MSSV: 21850024

Họ và tên: Nguyễn Minh Tư

In [2]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np
import pandas as pd

## Câu 1 (2 đ)

Tạo `mat` là một ma trận kích thước 4x6 gồm các số nguyên với phần tử ở dòng $i$, cột $j$ là $10i + j$ (chỉ số dòng, cột tính từ 1). Thực hiện các thao tác sau trên ma trận `mat`

1. Xuất ra dòng 2 và cột 3

1. Xuất ra phần tử ở dòng cuối, cột cuối

1. Xuất ra nửa trái của

1. Tính tổng các phần tử trên mỗi dòng

1. Trừ mỗi dòng một lượng là trung bình trên từng cột (canh giữa dữ liệu, centering)

1. Đặt tất cả các phần tử dòng cuối là 0

1. Đặt tất cả các phần tử trên đường chéo chính là 1

1. Tách theo chiều dọc thành 2 ma trận con lần lượt gồm 2 cột và 4 cột

1. Tách theo chiều ngang thành 2 ma trận con 2 dòng

1. Đổi dạng thành tensor 2x3x4

In [4]:
# Tạo ma trận mat với kích thước 4x6, phần tử tại vị trí i, j là 10i + j (i, j tính từ 1)
mat = np.array([[10 * i + j for j in range(1, 7)] for i in range(1, 5)])
print('Tạo ma trận mat với kích thước 4x6, phần tử tại vị trí i, j là 10i + j (i, j tính từ 1): \n', mat)

# 1. Xuất ra dòng 2 và cột 3
row_2_col_3 = mat[1, 2]
print('1. Xuất ra dòng 2 và cột 3: ', row_2_col_3)

# 2. Xuất ra phần tử ở dòng cuối, cột cuối
last_element = mat[-1, -1]
print('2. Xuất ra phần tử ở dòng cuối, cột cuối: ', last_element)

# 3. Xuất ra nửa trái của ma trận
left_half = mat[:, :mat.shape[1]//2]
print('3. Xuất ra nửa trái của ma trận: \n', left_half)

# 4. Tính tổng các phần tử trên mỗi dòng, (axis = 1: theo hàng, axis = 0: theo cột)
row_sum = np.sum(mat, axis=1)
print('4. Tính tổng các phần tử trên mỗi dòng: ', row_sum)

# 5. Trừ mỗi dòng một lượng là trung bình trên từng cột (canh giữa dữ liệu)
column_means = np.mean(mat, axis=0)
print('5. Trung bình trên từng cột: ', column_means)
centered_mat = mat - column_means
print('5. Ma trận sau khi canh giữa dữ liệu (trừ trung bình cột): \n', centered_mat)

# 6. Đặt tất cả các phần tử dòng cuối là 0
mat_with_zero_last_row = mat.copy()
mat_with_zero_last_row[-1, :] = 0
print('6. Ma trận với dòng cuối đặt tất cả phần tử là 0: \n', mat_with_zero_last_row)

# 7. Đặt tất cả các phần tử trên đường chéo chính là 1
mat_with_diagonal_one = mat.copy()
np.fill_diagonal(mat_with_diagonal_one, 1)
print('7. Ma trận với đường chéo chính là 1: \n', mat_with_diagonal_one)

# 8. Tách theo chiều dọc thành 2 ma trận con lần lượt gồm 2 cột và 4 cột
split_vertical = np.hsplit(mat, [2])
print('8. Tách theo chiều dọc thành 2 ma trận con: \nMa trận 1: \n', split_vertical[0], '\nMa trận 2: \n', split_vertical[1])

# 9. Tách theo chiều ngang thành 2 ma trận con 2 dòng
split_horizontal = np.vsplit(mat, [2])
print('9. Tách theo chiều ngang thành 2 ma trận con: \nMa trận 1: \n', split_horizontal[0], '\nMa trận 2: \n', split_horizontal[1])

# 10. Đổi dạng thành tensor 2x3x4
tensor_2x3x4 = mat.reshape(2, 3, 4)
print('10. Đổi dạng thành tensor 2x3x4: \n', tensor_2x3x4)

Tạo ma trận mat với kích thước 4x6, phần tử tại vị trí i, j là 10i + j (i, j tính từ 1): 
 [[11 12 13 14 15 16]
 [21 22 23 24 25 26]
 [31 32 33 34 35 36]
 [41 42 43 44 45 46]]
1. Xuất ra dòng 2 và cột 3:  23
2. Xuất ra phần tử ở dòng cuối, cột cuối:  46
3. Xuất ra nửa trái của ma trận: 
 [[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]
4. Tính tổng các phần tử trên mỗi dòng:  [ 81 141 201 261]
5. Trung bình trên từng cột:  [26. 27. 28. 29. 30. 31.]
5. Ma trận sau khi canh giữa dữ liệu (trừ trung bình cột): 
 [[-15. -15. -15. -15. -15. -15.]
 [ -5.  -5.  -5.  -5.  -5.  -5.]
 [  5.   5.   5.   5.   5.   5.]
 [ 15.  15.  15.  15.  15.  15.]]
6. Ma trận với dòng cuối đặt tất cả phần tử là 0: 
 [[11 12 13 14 15 16]
 [21 22 23 24 25 26]
 [31 32 33 34 35 36]
 [ 0  0  0  0  0  0]]
7. Ma trận với đường chéo chính là 1: 
 [[ 1 12 13 14 15 16]
 [21  1 23 24 25 26]
 [31 32  1 34 35 36]
 [41 42 43  1 45 46]]
8. Tách theo chiều dọc thành 2 ma trận con: 
Ma trận 1: 
 [[11 12]
 [21 22]
 [31 32]
 [41 4

## Câu 2 (4 đ)

1. Tìm hiểu bộ dữ liệu `Breast Cancer Wisconsin (Original)` (https://archive.ics.uci.edu/dataset/15/breast+cancer+wisconsin+original)

1. Download tập tin dữ liệu `breast+cancer+wisconsin+original.zip` (https://archive.ics.uci.edu/static/public/15/breast+cancer+wisconsin+original.zip), lấy ra tập tin `breast-cancer-wisconsin.data` và nạp dữ liệu vào `DataFrame` tên là `breast_cancer`, kiểm tra thông tin của bảng dữ liệu nạp được

1. Lưu ý là bộ dữ liệu này có ô bị thiếu (đánh dấu bằng dấu ?), nạp lại dữ liệu cho đúng và kiểm tra lại thông tin của bảng dữ liệu

1. Kiểm tra có bao nhiêu ô NA, bao nhiêu dòng có chứa NA, bao nhiêu cột có chứa NA và tìm chiến lược xử lý NA phù hợp (xóa các dòng chứa NA hay xóa các cột chứa NA hay điền giá trị cho NA với các chiến lược khác nhau)

1. Tính tỉ lệ mẫu ác tính (`class` là 4 = malignant) và sửa lại cột `class` với giá trị 1 là ác tính và 0 là lành tính

1. Dùng phương thức `describe` mô tả toàn bộ dữ liệu và dữ liệu tách riêng theo lành tính và ác tính. Nhận xét.

1. Xét riêng đặc trưng (cột) `Clump Thickness`, tính trung bình cho toàn bộ dữ liệu và dữ liệu tách riêng theo lành tính và ác tính. Nhận xét. Đặc trưng `Clump Thickness` có phản ánh nhiều khả năng ác tính không? Vì sao?

1. Đặc trưng nào liên quan nhiều nhất đến khả năng ác tính? Vì sao?

1. Gom nhóm dữ liệu theo `Clump Thickness` và tính tỉ lệ ác tính theo từng nhóm, nhận xét

1. Tương tự trên nhưng gom nhóm dữ liệu theo `Uniformity of Cell Size` và lần lượt theo `Clump Thickness`, `Uniformity of Cell Size`

In [47]:
# 1. Bộ dữ liệu Breast Cancer Wisconsin (Original) (https://archive.ics.uci.edu/dataset/15/breast+cancer+wisconsin+original) là một tập dữ liệu, thường được sử dụng trong các nghiên cứu và bài toán liên quan đến dự đoán ung thư vú. Bộ dữ liệu này được phát triển từ một nghiên cứu thực hiện tại Bệnh viện Đại học Wisconsin, nhằm chẩn đoán ung thư vú dựa trên các đặc trưng tế bào học của khối u.
    #a. Mô tả bộ dữ liệu:
        # - Nguồn gốc: Bộ dữ liệu được lấy từ các hình ảnh quét tế bào của khối u vú.
        # - Loại dữ liệu: Dữ liệu này thuộc phân loại với hai nhãn: lành tính và ác tính.
        # Các thông tin cụ thể về bộ dữ liệu:
        # Số lượng mẫu: 699 mẫu.
        # Số lượng thuộc tính: 11 thuộc tính (10 thuộc tính số + 1 thuộc tính ID).
        # Thuộc tính mục tiêu: Phân loại khối u thành hai loại:
            # 2: Lành tính (Benign)
            # 4: Ác tính (Malignant)
        # Các thuộc tính:
            # ID số (identifier): Là chỉ số định danh duy nhất cho mỗi bệnh nhân.
            # Clump Thickness: Độ dày khối u.
            # Uniformity of Cell Size: Độ đồng đều kích thước tế bào.
            # Uniformity of Cell Shape: Độ đồng đều hình dạng tế bào.
            # Marginal Adhesion: Mức độ kết dính của tế bào.
            # Single Epithelial Cell Size: Kích thước tế bào biểu mô đơn lẻ.
            # Bare Nuclei: Nhân trần (nuclei không có cytoplasm).
            # Bland Chromatin: Độ nhạt màu của chất nhiễm sắc.
            # Normal Nucleoli: Số lượng nucleoli bình thường.
            # Mitoses: Sự phân chia tế bào (số lần phân chia).
            # Class (Target): Mục tiêu phân loại, gồm hai giá trị:
                # 2: Lành tính
                # 4: Ác tính
    #b. Ý nghĩa các thuộc tính: Các thuộc tính này mô tả đặc trưng tế bào học của các khối u dựa trên ảnh quét tế bào. Chúng được đánh giá trên thang điểm từ 1 (rất ít nghi ngờ) đến 10 (rất nhiều nghi ngờ). Các đặc trưng này sau đó được sử dụng để dự đoán liệu khối u là lành tính hay ác tính.
    #c. Mục đích sử dụng:
        # Các mô hình học máy: Sử dụng để huấn luyện các mô hình phân loại (như hồi quy logistic, SVM, cây quyết định, mạng nơ-ron, v.v.) nhằm phân loại ung thư vú.
        # Bài toán chẩn đoán y học: Bộ dữ liệu này là nền tảng cho việc phát triển các hệ thống hỗ trợ quyết định trong y học, đặc biệt trong việc phát hiện sớm và phân loại ung thư.


In [48]:

# 2. Download tập tin dữ liệu `breast+cancer+wisconsin+original.zip` (https://archive.ics.uci.edu/static/public/15/breast+cancer+wisconsin+original.zip), lấy ra tập tin `breast-cancer-wisconsin.data` và nạp dữ liệu vào `DataFrame` tên là `breast_cancer`, kiểm tra thông tin của bảng dữ liệu nạp được

# Xác định đường dẫn của file cần lấy (breast-cancer-wisconsin.data)
data_file_path = "breast-cancer-wisconsin.data"

# Nạp dữ liệu từ file vào DataFrame
column_names = [
    "ID", "Clump Thickness", "Uniformity of Cell Size", "Uniformity of Cell Shape", 
    "Marginal Adhesion", "Single Epithelial Cell Size", "Bare Nuclei", 
    "Bland Chromatin", "Normal Nucleoli", "Mitoses", "Class"
]
breast_cancer = pd.read_csv(data_file_path, names=column_names)
# print(breast_cancer)


In [49]:

# 3. Lưu ý là bộ dữ liệu này có ô bị thiếu (đánh dấu bằng dấu ?), nạp lại dữ liệu cho đúng và kiểm tra lại thông tin của bảng dữ liệu
breast_cancer.replace('?', pd.NA, inplace=True)

# 4. Kiểm tra các hàng có giá trị NaN
print(f"Các hàng có giá trị NULL: \n {breast_cancer.isnull().sum()}")

# Cách 1: Xóa những hàng có dữ liệu bị thiếu
# breast_cancer_cleaned = breast_cancer.dropna()

# Kiểm tra dữ liệu
# print(breast_cancer_cleaned.isna().sum())

# Cách 2: Chuyển column 'Bare Nuclei' sang kiểu dữ liệu số, cài đặt errors='coerce' để xử lý cú pháp không hợp lệ, ví dụ '?' thành NaN
breast_cancer['Bare Nuclei'] = pd.to_numeric(breast_cancer['Bare Nuclei'], errors='coerce')

# Chỉ điền các giá trị (NaN) còn thiếu bằng giá trị trung bình của Bare Nuclei
median_value = breast_cancer['Bare Nuclei'].median()
breast_cancer['Bare Nuclei'].fillna(median_value, inplace=True)

# Kiểm tra dữ liệu
print("\n")
print(f"Các hàng có giá trị NULL sau khi xử lý lại dữ liệu: \n {breast_cancer.isnull().sum()}")


Các hàng có giá trị NULL: 
 ID                              0
Clump Thickness                 0
Uniformity of Cell Size         0
Uniformity of Cell Shape        0
Marginal Adhesion               0
Single Epithelial Cell Size     0
Bare Nuclei                    16
Bland Chromatin                 0
Normal Nucleoli                 0
Mitoses                         0
Class                           0
dtype: int64


Các hàng có giá trị NULL sau khi xử lý lại dữ liệu: 
 ID                             0
Clump Thickness                0
Uniformity of Cell Size        0
Uniformity of Cell Shape       0
Marginal Adhesion              0
Single Epithelial Cell Size    0
Bare Nuclei                    0
Bland Chromatin                0
Normal Nucleoli                0
Mitoses                        0
Class                          0
dtype: int64


C:\Users\nguye\AppData\Local\Temp\ipykernel_30332\2513502610.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  breast_cancer['Bare Nuclei'].fillna(median_value, inplace=True)


In [50]:
# 5. Tính tỉ lệ mẫu ác tính (`class` là 4 = malignant) và sửa lại cột `class` với giá trị 1 là ác tính và 0 là lành tính

# Bước 1: Tính tỉ lệ mẫu ác tính (Class == 4)

total_samples = breast_cancer.shape[0]  # Tổng số hàng/mẫu
malignant_samples = breast_cancer[breast_cancer['Class'] == 4].shape[0]  # Mẫu ác tính (Class == 4)
malignant_ratio = malignant_samples / total_samples  # Tỷ lệ của mẫu ác tính

print(f"Tổng số lượng mẫu: {total_samples}")
print(f"Số lượng mẫu ác tính: {malignant_samples}")
print(f"Tỉ lệ mẫu ác tính: {malignant_ratio:.2%}")  

# Bước 2: sửa lại cột `class` với 1 = ác tính và 0 = lành tính
breast_cancer['Class'] = breast_cancer['Class'].map({2: 0, 4: 1})

# Kiểm tra dữ liệu
print(breast_cancer['Class'].value_counts())


Tổng số lượng mẫu: 699
Số lượng mẫu ác tính: 241
Tỉ lệ mẫu ác tính: 34.48%
Class
0    458
1    241
Name: count, dtype: int64


In [51]:
# 6. Dùng phương thức `describe` mô tả toàn bộ dữ liệu và dữ liệu tách riêng theo lành tính và ác tính. Nhận xét.
# Bước 1: Dùng describe() để mô tả toàn bộ dữ liệu
print("Mô tả toàn bộ dữ liệu:")
print(breast_cancer.describe())

# Bước 2: Mô tả riêng dữ liệu lành tính (Class == 0)
print("\nMô tả dữ liệu lành tính (Class == 0):")
print(breast_cancer[breast_cancer['Class'] == 0].describe())

# Bước 3: Mô tả riêng dữ liệu ác tính (Class == 1)
print("\nMô tả dữ liệu ác tính (Class == 1):")
print(breast_cancer[breast_cancer['Class'] == 1].describe())

# Nhận xét về mô tả toàn bộ dữ liệu
print("Nhận xét về mô tả toàn bộ dữ liệu:")
print("1. Dữ liệu có tổng cộng 699 mẫu, với các đặc trưng như 'Clump Thickness' và 'Uniformity of Cell Size' có giá trị dao động từ 1 đến 10.")
print("2. Giá trị trung bình của 'Clump Thickness' là {:.2f}, cho thấy độ dày khối u trung bình ở các mẫu.".format(breast_cancer['Clump Thickness'].mean()))
print("3. Giá trị trung bình của 'Uniformity of Cell Size' là {:.2f}, cho thấy sự đồng nhất kích thước tế bào trung bình.".format(breast_cancer['Uniformity of Cell Size'].mean()))
print("4. Có sự chênh lệch đáng kể giữa các giá trị tối thiểu và tối đa trong cả hai đặc trưng, cho thấy sự đa dạng trong mẫu dữ liệu.".format(breast_cancer['Uniformity of Cell Size'].min(), breast_cancer['Uniformity of Cell Size'].max()))

# Nhận xét về dữ liệu lành tính (Class == 0)
print("\nNhận xét về dữ liệu lành tính (Class == 0):")
print("1. Dữ liệu lành tính có tổng cộng 458 mẫu với độ dày khối u trung bình là {:.2f}.".format(breast_cancer[breast_cancer['Class'] == 0]['Clump Thickness'].mean()))
print("2. Sự đồng nhất kích thước tế bào trung bình là {:.2f}.".format(breast_cancer[breast_cancer['Class'] == 0]['Uniformity of Cell Size'].mean()))
print("3. Từ các chỉ số này, có thể thấy rằng các mẫu lành tính có các giá trị thấp hơn cho cả 'Clump Thickness' và 'Uniformity of Cell Size'.".format())

# Nhận xét về dữ liệu ác tính (Class == 1)
print("\nNhận xét về dữ liệu ác tính (Class == 1):")
print("1. Dữ liệu ác tính có tổng cộng 241 mẫu với độ dày khối u trung bình là {:.2f}.".format(breast_cancer[breast_cancer['Class'] == 1]['Clump Thickness'].mean()))
print("2. Sự đồng nhất kích thước tế bào trung bình là {:.2f}.".format(breast_cancer[breast_cancer['Class'] == 1]['Uniformity of Cell Size'].mean()))
print("3. Các mẫu ác tính có giá trị cao hơn cho cả hai đặc trưng, cho thấy mối liên hệ tích cực giữa độ dày và khả năng ác tính.".format())

# Tổng kết
print("\nTổng kết:")
print("Sự chênh lệch rõ rệt giữa các mẫu lành tính và ác tính cho thấy rằng cả 'Clump Thickness' và 'Uniformity of Cell Size' là những chỉ số quan trọng trong việc xác định khả năng ác tính của khối u.")
print("Việc sử dụng những đặc trưng này có thể giúp trong việc phát hiện sớm và chẩn đoán bệnh ung thư.")


Mô tả toàn bộ dữ liệu:
                 ID  Clump Thickness  Uniformity of Cell Size  \
count  6.990000e+02       699.000000               699.000000   
mean   1.071704e+06         4.417740                 3.134478   
std    6.170957e+05         2.815741                 3.051459   
min    6.163400e+04         1.000000                 1.000000   
25%    8.706885e+05         2.000000                 1.000000   
50%    1.171710e+06         4.000000                 1.000000   
75%    1.238298e+06         6.000000                 5.000000   
max    1.345435e+07        10.000000                10.000000   

       Uniformity of Cell Shape  Marginal Adhesion  \
count                699.000000         699.000000   
mean                   3.207439           2.806867   
std                    2.971913           2.855379   
min                    1.000000           1.000000   
25%                    1.000000           1.000000   
50%                    1.000000           1.000000   
75%          

In [52]:
# 7. Xét riêng đặc trưng (cột) `Clump Thickness`, tính trung bình cho toàn bộ dữ liệu và dữ liệu tách riêng theo lành tính và ác tính. Nhận xét. Đặc trưng `Clump Thickness` có phản ánh nhiều khả năng ác tính không? Vì sao?

# Bước 1: Tính trung bình của cột 'Clump Thickness' cho toàn bộ dữ liệu
mean_clump_thickness_all = breast_cancer['Clump Thickness'].mean()

# Bước 2: Tính trung bình riêng cho dữ liệu lành tính (Class == 0) và ác tính (Class == 1)
mean_clump_thickness_benign = breast_cancer[breast_cancer['Class'] == 0]['Clump Thickness'].mean()
mean_clump_thickness_malignant = breast_cancer[breast_cancer['Class'] == 1]['Clump Thickness'].mean()

# Bước 3: Hiển thị kết quả
print(f"Trung bình 'Clump Thickness' cho toàn bộ dữ liệu: {mean_clump_thickness_all}")
print(f"Trung bình 'Clump Thickness' cho dữ liệu lành tính: {mean_clump_thickness_benign}")
print(f"Trung bình 'Clump Thickness' cho dữ liệu ác tính: {mean_clump_thickness_malignant}")

# Nhận xét
if mean_clump_thickness_malignant > mean_clump_thickness_benign:
    print("Đặc trưng 'Clump Thickness' có xu hướng cao hơn trong các mẫu ác tính, phản ánh khả năng ác tính.")
else:
    print("Đặc trưng 'Clump Thickness' không phản ánh rõ ràng khả năng ác tính.")


Trung bình 'Clump Thickness' cho toàn bộ dữ liệu: 4.417739628040057
Trung bình 'Clump Thickness' cho dữ liệu lành tính: 2.9563318777292578
Trung bình 'Clump Thickness' cho dữ liệu ác tính: 7.195020746887967
Đặc trưng 'Clump Thickness' có xu hướng cao hơn trong các mẫu ác tính, phản ánh khả năng ác tính.


In [53]:
# 8. Đặc trưng nào liên quan nhiều nhất đến khả năng ác tính? Vì sao?
print("Dựa trên phân tích, Clump Thickness là đặc trưng có liên quan mạnh mẽ nhất đến khả năng ác tính trong ung thư vú. Giá trị cao của Clump Thickness thường đi kèm với nguy cơ ác tính cao hơn. Tuy nhiên, để có kết luận chính xác và toàn diện, cần kết hợp phân tích thêm các đặc trưng khác và sử dụng các phương pháp thống kê phù hợp. Ví dụ như: Uniformity of Cell Size, và Bare Nuclei thường là những đặc trưng cũng có liên quan nhiều nhất đến khả năng ác tính, vì chúng thể hiện sự bất thường và thay đổi hình thái của tế bào, một dấu hiệu thường gặp ở các tế bào ung thư.")

Dựa trên phân tích, Clump Thickness là đặc trưng có liên quan mạnh mẽ nhất đến khả năng ác tính trong ung thư vú. Giá trị cao của Clump Thickness thường đi kèm với nguy cơ ác tính cao hơn. Tuy nhiên, để có kết luận chính xác và toàn diện, cần kết hợp phân tích thêm các đặc trưng khác và sử dụng các phương pháp thống kê phù hợp. Ví dụ như: Uniformity of Cell Size, và Bare Nuclei thường là những đặc trưng cũng có liên quan nhiều nhất đến khả năng ác tính, vì chúng thể hiện sự bất thường và thay đổi hình thái của tế bào, một dấu hiệu thường gặp ở các tế bào ung thư.


In [54]:
# 9. Gom nhóm dữ liệu theo `Clump Thickness` và tính tỉ lệ ác tính theo từng nhóm, nhận xét
# Bước 1: Gom nhóm dữ liệu theo 'Clump Thickness'
clump_thickness_grouped_data = breast_cancer.groupby('Clump Thickness')

# Bước 2: Tính tỷ lệ ác tính cho từng nhóm
# Đếm số lượng mẫu ác tính (Class == 1) và tổng số mẫu trong từng nhóm
malignant_counts = clump_thickness_grouped_data['Class'].apply(lambda x: (x == 1).sum())  # Số lượng mẫu ác tính
total_counts = clump_thickness_grouped_data['Class'].count()    # Tổng số mẫu trong mỗi nhóm

# Tính tỷ lệ ác tính cho từng nhóm
malignant_rate_per_clump_thickness_group = malignant_counts / total_counts
print("Tỷ lệ ác tính theo từng nhóm Clump Thickness:")
print(malignant_rate_per_clump_thickness_group)

# Nhận xét:
print("Nhận xét Clump Thickness: Sau khi tính toán, ta có thể thấy rằng tỉ lệ ác tính có thể tăng dần theo Clump Thickness. Điều này có nghĩa là khi độ dày của khối u tăng lên, khả năng mẫu ác tính của tăng theo.  Các nhóm có Clump Thickness lớn hơn có thể tỷ lệ ác tính cao hơn, cho thấy sự liên quan của đặc trưng này với ung thư ác tính")

Tỷ lệ ác tính theo từng nhóm Clump Thickness:
Clump Thickness
1     0.020690
2     0.080000
3     0.111111
4     0.150000
5     0.346154
6     0.529412
7     0.956522
8     0.913043
9     1.000000
10    1.000000
Name: Class, dtype: float64
Nhận xét Clump Thickness: Sau khi tính toán, ta có thể thấy rằng tỉ lệ ác tính có thể tăng dần theo Clump Thickness. Điều này có nghĩa là khi độ dày của khối u tăng lên, khả năng mẫu ác tính của tăng theo.  Các nhóm có Clump Thickness lớn hơn có thể tỷ lệ ác tính cao hơn, cho thấy sự liên quan của đặc trưng này với ung thư ác tính


In [55]:
# 10. Tương tự trên nhưng gom nhóm dữ liệu theo `Uniformity of Cell Size` và lần lượt theo `Clump Thickness`, `Uniformity of Cell Size`
# Bước 1: Gom nhóm dữ liệu theo 'Uniformity of Cell Size'
grouped_by_size = breast_cancer.groupby('Uniformity of Cell Size')

# Bước 2: Tính tỷ lệ ác tính cho từng nhóm
malignant_counts_size = grouped_by_size['Class'].apply(lambda x: (x == 1).sum())  # Số lượng mẫu ác tính
total_counts_size = grouped_by_size['Class'].count()    # Tổng số mẫu trong mỗi nhóm

# Tính tỷ lệ ác tính cho từng nhóm
malignant_rate_per_group_size = malignant_counts_size / total_counts_size

# Hiển thị tỷ lệ ác tính theo từng nhóm 'Uniformity of Cell Size'
print("Tỷ lệ ác tính theo từng nhóm Uniformity of Cell Size:")
print(malignant_rate_per_group_size)

# Nhận xét:
print("Nhận xét dữ liệu theo nhóm Uniformity of Cell Size: 1. Xu hướng Tăng: Tỷ lệ ác tính tăng dần từ nhóm 1 đến nhóm 10. Điều này cho thấy rằng khi Uniformity of Cell Size tăng (nghĩa là sự đồng nhất của kích thước tế bào giảm), khả năng ác tính của mẫu tăng lên. 2. Giá trị cao: Từ giá trị 5 trở đi, tỷ lệ ác tính gần như đạt đến 1.00, tức là hầu như tất cả các mẫu trong các nhóm này đều ác tính. Điều này gợi ý rằng sự không đồng nhất của kích thước tế bào có thể là một yếu tố quan trọng trong việc xác định khả năng ác tính.")

# Gom nhóm dữ liệu theo `Clump Thickness`, `Uniformity of Cell Size`
# Bước 1: Gom nhóm dữ liệu theo 'Clump Thickness' và 'Uniformity of Cell Size'
grouped_by_thickness_size = breast_cancer.groupby(['Clump Thickness', 'Uniformity of Cell Size'])

# Bước 2: Tính tỷ lệ ác tính cho từng nhóm
malignant_counts_thickness_size = grouped_by_thickness_size['Class'].apply(lambda x: (x == 1).sum())  # Số lượng mẫu ác tính
total_counts_thickness_size = grouped_by_thickness_size['Class'].count()    # Tổng số mẫu trong mỗi nhóm

# Tính tỷ lệ ác tính cho từng nhóm
malignant_rate_per_group_thickness_size = malignant_counts_thickness_size / total_counts_thickness_size

# Hiển thị tỷ lệ ác tính theo từng nhóm 'Clump Thickness' và 'Uniformity of Cell Size'
print("Tỷ lệ ác tính theo từng nhóm Clump Thickness và Uniformity of Cell Size:")
print(malignant_rate_per_group_thickness_size)

print("Nhận xét dữ liệu theo nhóm Clump Thickness và Uniformity of Cell Size: Có thể thấy rằng trong các nhóm Clump Thickness thấp, tỷ lệ ác tính có thể thấp, nhưng khi Clump Thickness và Uniformity of Cell Size cùng tăng, tỷ lệ ác tính có xu hướng tăng mạnh. Điều này chỉ ra rằng không chỉ riêng Clump Thickness mà sự kết hợp giữa hai đặc trưng này đóng vai trò quan trọng trong việc xác định khả năng ác tính. Ví dụ: Nếu nhóm có Clump Thickness từ 7 đến 10 và Uniformity of Cell Size từ 7 đến 10 có tỷ lệ ác tính rất cao (ví dụ: > 0.80), thì có thể kết luận rằng cả hai yếu tố này đều có ảnh hưởng lớn đến khả năng ác tính của mẫu.")

Tỷ lệ ác tính theo từng nhóm Uniformity of Cell Size:
Uniformity of Cell Size
1     0.010417
2     0.177778
3     0.480769
4     0.775000
5     1.000000
6     0.925926
7     0.947368
8     0.965517
9     0.833333
10    1.000000
Name: Class, dtype: float64
Nhận xét dữ liệu theo nhóm Uniformity of Cell Size: 1. Xu hướng Tăng: Tỷ lệ ác tính tăng dần từ nhóm 1 đến nhóm 10. Điều này cho thấy rằng khi Uniformity of Cell Size tăng (nghĩa là sự đồng nhất của kích thước tế bào giảm), khả năng ác tính của mẫu tăng lên. 2. Giá trị cao: Từ giá trị 5 trở đi, tỷ lệ ác tính gần như đạt đến 1.00, tức là hầu như tất cả các mẫu trong các nhóm này đều ác tính. Điều này gợi ý rằng sự không đồng nhất của kích thước tế bào có thể là một yếu tố quan trọng trong việc xác định khả năng ác tính.
Tỷ lệ ác tính theo từng nhóm Clump Thickness và Uniformity of Cell Size:
Clump Thickness  Uniformity of Cell Size
1                1                          0.0
                 2                          0.0
         

## Câu 3 (4 đ)

**3.1. (0.5 đ)** Tạo bảng dữ liệu SUPPLIER cho biết thông tin các hãng cung ứng sản phẩm như sau:

S# | NAME   | STATUS |	CITY
---|--------|--------|-------
S1 | Smith	| 20     | London
S2 | Jones  | 10     | Paris
S3 | Blacke | 25     | London

Trong đó:
  - S# là mã nhà cung ứng
  - NAME là tên nhà cung ứng
  - STATUS cho biết qui mô nhà cung ứng
  - CITY cho biết thành phố đặt trụ sở

In [36]:
# Tạo dữ liệu cho bảng SUPPLIER
supplier_data = {
    'S#': ['S1', 'S2', 'S3'],
    'NAME': ['Smith', 'Jones', 'Blacke'],
    'STATUS': [20, 10, 25],
    'CITY': ['London', 'Paris', 'London']
}

# Tạo DataFrame
supplier_df = pd.DataFrame(supplier_data)

# Hiển thị DataFrame
print(supplier_df)

   S#    NAME  STATUS    CITY
0  S1   Smith      20  London
1  S2   Jones      10   Paris
2  S3  Blacke      25  London


**3.2. (0.5 đ)** Tạo bảng dữ liệu PRODUCT cho biết thông tin các sản phẩm như sau:

P# | NAME   | COLOR | WEIGHT | CITY
---|--------|-------|--------|-----
P1 | Nut	| Red   | 13     | London
P2 | Screw   | Green | 17     | Paris
P3 | Screw  | Blue  | 14     | Roma
P4 | Bolt  | Red   | 17     | London

Trong đó:
  - P# là mã sản phẩm
  - NAME là tên sản phẩm
  - COLOR là màu sản phẩm
  - WEIGHT cho biết trọng lượng sản phẩm
  - CITY cho biết nơi bán sản phẩm

In [37]:
# Tạo dữ liệu cho bảng PRODUCT
product_data = {
    'P#': ['P1', 'P2', 'P3', 'P4'],
    'NAME': ['Nut', 'Screw', 'Screw', 'Bolt'],
    'COLOR': ['Red', 'Green', 'Blue', 'Red'],
    'WEIGHT': [13, 17, 14, 17],
    'CITY': ['London', 'Paris', 'Roma', 'London']
}

# Tạo DataFrame
product_df = pd.DataFrame(product_data)

# Hiển thị DataFrame
print(product_df)

   P#   NAME  COLOR  WEIGHT    CITY
0  P1    Nut    Red      13  London
1  P2  Screw  Green      17   Paris
2  P3  Screw   Blue      14    Roma
3  P4   Bolt    Red      17  London


**3.3. (0.5 đ)** Tạo bảng dữ liệu SUPPLIES cho biết thông tin các cung ứng như sau:

S# | P# | QTY
---|----|-----
S1 | P2	| 200
S1 | P1 | 200
S1 | P3 | 400
S2 | P1 | 300
S3 | P1 | 400
S3 | P2 | 200

Trong đó:
  - S# là mã nhà cung ứng
  - P# là mã sản phẩm
  - QTY là số lượng sản phẩm được cung ứng

In [38]:
# Tạo dữ liệu cho bảng SUPPLIES
supplies_data = {
    'S#': ['S1', 'S1', 'S1', 'S2', 'S3', 'S3'],
    'P#': ['P2', 'P1', 'P3', 'P1', 'P1', 'P2'],
    'QTY': [200, 200, 400, 300, 400, 200]
}

# Tạo DataFrame
supplies_df = pd.DataFrame(supplies_data)

# Hiển thị DataFrame
print(supplies_df)

   S#  P#  QTY
0  S1  P2  200
1  S1  P1  200
2  S1  P3  400
3  S2  P1  300
4  S3  P1  400
5  S3  P2  200


**3.4. (2.5 đ)** Từ 3 bảng trên, thực hiện các truy vấn dữ liệu sau (có thể viết thêm các hàm phụ nếu cần):

1.	Đưa ra danh sách các hãng cung ứng có trụ sở (CITY) ở London.

1.	Đưa ra tên (NAME) của các sản phẩm có trọng lượng (WEIGHT) lớn hơn 14 và có màu (COLOR) đỏ (Red).

1.	Đưa ra tên (NAME) của hãng có STATUS lớn nhất.

1.	Đưa ra tên của các hãng cung ứng mặt hàng Nut hoặc Bolt.

1.	Đưa ra tên của các hãng cung ứng ít nhất một mặt hàng màu đỏ.

1. Đưa ra tên của hãng cung ứng mặt hàng Nut với số lượng nhiều nhất.

1.	Đưa ra tên của các hãng cung ứng ít nhất hai mặt hàng.

1. Đưa ra tên của các mặt hàng được cung ứng bởi tất cả các hãng. 

In [39]:
london_suppliers = supplier_df[supplier_df['CITY'] == 'London']
print("Hãng cung ứng ở London:")
print(london_suppliers[['NAME']])

Hãng cung ứng ở London:
     NAME
0   Smith
2  Blacke


In [40]:
red_products = product_df[(product_df['WEIGHT'] > 14) & (product_df['COLOR'] == 'Red')]
print("\nSản phẩm màu đỏ có trọng lượng lớn hơn 14:")
print(red_products[['NAME']])


Sản phẩm màu đỏ có trọng lượng lớn hơn 14:
   NAME
3  Bolt


In [41]:
max_status_supplier = supplier_df[supplier_df['STATUS'] == supplier_df['STATUS'].max()]
print("\nHãng có STATUS lớn nhất:")
print(max_status_supplier[['NAME']])


Hãng có STATUS lớn nhất:
     NAME
2  Blacke


In [42]:
# nut_bolt_suppliers = supplies_df[supplies_df['P#'].isin(['P1', 'P4'])]
# nut_bolt_suppliers = supplier_df[supplier_df['S#'].isin(nut_bolt_suppliers['S#'])]
# print("\nHãng cung ứng mặt hàng Nut hoặc Bolt:")
# print(nut_bolt_suppliers[['NAME']])


Hãng cung ứng mặt hàng Nut hoặc Bolt:
     NAME
0   Smith
1   Jones
2  Blacke


In [83]:
supplies_products = pd.merge(supplies_df, product_df, on='P#', suffixes=('_supplies', '_products'))
# print(supplies_products)
supplier_details = pd.merge(supplier_df, supplies_products, on='S#', suffixes=('_supplier', '_products'))
# print(supplier_details)
filtered_suppliers = supplier_details[supplier_details['NAME_products'].isin(['Nut', 'Bolt'])]
# print(filtered_suppliers)

print("\nHãng cung ứng mặt hàng Nut hoặc Bolt:")
print(filtered_suppliers[['NAME_supplier']])


Hãng cung ứng mặt hàng Nut hoặc Bolt:
  NAME_supplier
1         Smith
3         Jones
4        Blacke


In [43]:
red_item_suppliers = supplies_df[supplies_df['P#'].isin(product_df[product_df['COLOR'] == 'Red']['P#'])]
red_item_suppliers = supplier_df[supplier_df['S#'].isin(red_item_suppliers['S#'])]
print("\nHãng cung ứng ít nhất một mặt hàng màu đỏ:")
print(red_item_suppliers[['NAME']])


Hãng cung ứng ít nhất một mặt hàng màu đỏ:
     NAME
0   Smith
1   Jones
2  Blacke


In [91]:
# nut_supplies = supplies_df[supplies_df['P#'] == 'P1']
nut_supplies = supplies_products[supplies_products['NAME'] == 'Nut']
max_qty = nut_supplies['QTY'].max()
max_qty_suppliers = nut_supplies[nut_supplies['QTY'] == max_qty]
suppliers_details = pd.merge(supplier_df, max_qty_suppliers, on='S#', suffixes=('_supplier', '_max_qty_supplier'))
# print(suppliers_details)
# print(suppliers_details.columns)
print("\nHãng cung ứng mặt hàng Nut với số lượng nhiều nhất:")
print(suppliers_details[['NAME_supplier']])


Hãng cung ứng mặt hàng Nut với số lượng nhiều nhất:
  NAME_supplier
0        Blacke


In [92]:
supplier_item_count = supplies_df.groupby('S#').size()
multiple_items_suppliers = supplier_item_count[supplier_item_count >= 2].index
suppliers_with_multiple_items = supplier_df[supplier_df['S#'].isin(multiple_items_suppliers)]
print("\nHãng cung ứng ít nhất hai mặt hàng:")
print(suppliers_with_multiple_items[['NAME']])


Hãng cung ứng ít nhất hai mặt hàng:
     NAME
0   Smith
2  Blacke


In [94]:
all_suppliers = set(supplies_df['S#'])
products_by_all_suppliers = supplies_df.groupby('P#').filter(lambda x: set(x['S#']) == all_suppliers)
products_available_for_all = product_df[product_df['P#'].isin(products_by_all_suppliers['P#'])]
print("\nMặt hàng được cung ứng bởi tất cả các hãng:")
print(products_available_for_all[['NAME']])


Mặt hàng được cung ứng bởi tất cả các hãng:
  NAME
0  Nut
